name: Webapp Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
      - '.github/workflows/webapp.yml'
  workflow_dispatch:

permissions:
  packages: write
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_ACTOR,,}" >> ${GITHUB_ENV}

      # - name: Terraform Init
      #   run: |
      #     cd terraform
      #     terraform init -input=false -backend-config="key=${{ env.REPO }}-terraform.tfstate"

      # - name: Get ACR Login Server from Terraform Output
      #   id: get_acr_login_server
      #   run: echo "acr_login_server=${{ steps.terraform.outputs.acr_login_server }}" >> $GITHUB_ENV

      - name: Login to Azure Container Registry using OIDC
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.REPO }}:latest ./webapp
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.REPO }}:latest